# Generated by Django 4.2.14 on 2024-08-13 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique_for_date='created-on')),
                ('genre', models.CharField(choices=[('Local Government', 'Local Government'), ('National News', 'National News'), ('Tech', 'Tech'), ('Local Events', 'Local Events'), ('Reguional Affairs', 'Regional Affairs'), ('Business', 'Business'), ('Food', 'Food'), ('Tourism', 'Tourism'), ('Sports', 'Sports'), ('Arts and Culture', 'Arts and Culture'), ('Finance', 'Finance'), ('Crime', 'Crime')], max_length=50)),
                ('byline', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
