# Generated by Django 4.2.14 on 2024-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.TextField(help_text='The name of your event', max_length=200)),
                ('AddressLine1', models.TextField(help_text='The first line of your event address, including street number', max_length=150)),
                ('AddressLine2', models.TextField(help_text='The second line of your event address', max_length=150)),
                ('Postcode', models.TextField(help_text='The postcode of your event address', max_length=8)),
                ('Online', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', help_text='Whether your event is online or offline', max_length=7)),
                ('EventDate', models.DateTimeField(help_text='What date is your event being held?')),
                ('EventTime', models.CharField(choices=[('06:00', '6AM'), ('07:00', '7AM'), ('08:00', '8AM'), ('09:00', '9AM'), ('10:00', '10AM'), ('11:00', '11AM'), ('12:00', '12PM'), ('13:00', '1PM'), ('14:00', '2PM'), ('15:00', '3PM'), ('16:00', '4PM'), ('17:00', '5PM'), ('18:00', '6PM'), ('19:00', '7PM'), ('20:00', '8PM'), ('21:00', '9PM'), ('22:00', '10PM'), ('23:00', '11PM'), ('24:00', '12AM'), ('01:00', '1AM'), ('02:00', '2AM'), ('03:00', '3AM'), ('04:00', '4AM'), ('05:00', '5AM')], default=0, max_length=24)),
                ('EventDescription', models.CharField(default='What will you be doing at this event?', max_length=400)),
            ],
        ),
    ]
