# Generated by Django 4.2.14 on 2024-08-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_remove_event_postcode_event_postcode_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventTime',
        ),
    ]
