# Generated by Django 4.2.14 on 2024-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_event_eventtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDescription',
            field=models.TextField(default='What will you be doing at this event?', max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventName',
            field=models.CharField(help_text='The name of your event', max_length=200),
        ),
    ]
